name: publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Set version
      if: ${{ github.event.release.tag_name }}
      run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }}

    - name: Publish package
      run: mvn -B -P release deploy
      env:
        MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
